apiVersion: 1

datasources:
  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    access: proxy
    url: http://victorialogs:9428
    jsonData:
      # Multitenancy settings, see https://docs.victoriametrics.com/victorialogs/#multitenancy
      # to use the multitenancy, uncomment lines below: AccountID and ProjectID
      multitenancyHeaders:
      #AccountID: 0
      #ProjectID: 0