spring:
  application:
    name: demo

management:
  otlp:
    metrics:
      export:
        url: http://localhost:8428/opentelemetry/v1/metrics
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: http://localhost:9428/insert/opentelemetry/v1/logs