services:
  victoria-logs:
    image: docker.io/victoriametrics/victoria-logs:v1.44.0
    container_name: victorialogs
    ports:
      - "9428:9428"
    volumes:
      - ./victoria-logs-data:/victoria-logs-data
    command:
      - "-storageDataPath=victoria-logs-data"
    stdin_open: true
    tty: true
    restart: always
    networks:
      - test-network

  victoria-metrics:
    image: victoriametrics/victoria-metrics:v1.134.0
    container_name: vm_single_node
    ports:
      - "8428:8428"
    volumes:
      - ./victoria-metrics-data:/victoria-metrics-data
    command:
      - "-storageDataPath=victoria-metrics-data"
    restart: unless-stopped
    networks:
      - test-network

  victoria-traces:
    image: docker.io/victoriametrics/victoria-traces:latest
    container_name: victoriatraces
    ports:
      - "10428:10428"
    volumes:
      - ./victoria-traces-data:/victoria-traces-data
    restart: unless-stopped
    networks:
      - test-network

  grafana:
    image: grafana/grafana:11.5.2
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_INSTALL_PLUGINS=victoriametrics-logs-datasource,victoriametrics-metrics-datasource
    depends_on:
      - victoria-logs
      - victoria-metrics
      - victoria-traces
    networks:
      - test-network

networks:
  test-network:
    driver: bridge
    name: test-network
